### Testfil för VSCode-tillägget REST Client

@baseUrl = http://localhost:8080
@userId = _
@token = _

### Users -> utan id = ger tillbaka ALLA user dokument
GET {{baseUrl}}/users
Authorization: Bearer {{token}} 

### Users -> med id = ger tillbaka ETT user dokument
GET {{baseUrl}}/users/{{userId}}
Authorization: Bearer {{token}} 

### Users -> skapa ny user
POST {{baseUrl}}/users
content-type: application/json

{
    "firstName": "test_first_name",
    "lastName": "test_last_name",
    "username": "test_username",
    "password": "test_password",
    "email": "test_email@email.com"
}

### Users -> updatera user
PUT {{baseUrl}}/users/{{userId}}
content-type: application/json
Authorization: Bearer {{token}} 

{
    "firstName": "test_first_name_modified",
    "lastName": "test_last_name_modified",
    "username": "test_username_modified",
    "password": "test_password_modified",
    "email": "test_email@email.com_modified"
}

### Users -> ta bort en user
DELETE {{baseUrl}}/users/{{userId}}
Authorization: Bearer {{token}} 

### Auth
POST {{baseUrl}}/auth
content-type: application/json

{
    "email": "test_email@email.com",
    "password": "test_password"
}