### Testfil för VSCode-tillägget REST Client

@baseUrl = http://localhost:8080
@cabinId = _
@token = _

### Cabin -> utan id = ger tillbaka ALLA cabin dokument
GET {{baseUrl}}/cabin
Authorization: Bearer {{token}}

### Cabin -> med id = ger tillbaka ETT cabin dokument
GET {{baseUrl}}/cabin/{{cabinId}}
Authorization: Bearer {{token}} 

### Cabin -> skapa ny cabin
POST {{baseUrl}}/cabin
content-type: application/json
Authorization: Bearer {{token}} 

{
    "address": "Testroad 5",
    "size": 2,
    "sauna": true,
    "price": 150
}

### Cabin -> updatera cabin
PUT {{baseUrl}}/cabin/{{cabinId}}
content-type: application/json
Authorization: Bearer {{token}} 

{
    "address": "Testroad 2",
    "size": 4,
    "sauna": false,
    "price": 300
}

### Cabin -> ta bort en cabin
DELETE {{baseUrl}}/cabin/{{cabinId}}
Authorization: Bearer {{token}} 