version: "3.9"

services:
    stugmaklare-api:
        container_name: "stugmaklare-api"
        # Lånat lite härifrån
        # https://github.com/nodejs/docker-node/blob/main/README.md#how-to-use-this-image
        build:
            context: .
            dockerfile: app/Dockerfile
        user: node
        restart: unless-stopped
        ports:
            - 8080:8080
        networks:
            stugmaklare-public:
            stugmaklare-private:
                ipv4_address: 10.0.0.2
        command: "npm start"
        profiles:
            - prod

    stugmaklare-db:
        # Lånat lite därifrån
        # https://hub.docker.com/_/mongo
        container_name: "stugmaklare-db"
        image: mongo:latest
        restart: unless-stopped
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: toor
        ports:
            - 27017:27017
        profiles:
            - prod
        networks:
            stugmaklare-private:
                ipv4_address: 10.0.0.3


    stugmaklare-api-dev:
    # !! OBS !! INSTALLERA PAKETEN LOKALT !! OBS !! NPM INSTALL KÖRS INTE I DENNA SERVICE !! OBS !!
    # samma som api bara att koden+node_modules mountas som volym istället, byggs även direkt från
    # node:latest istället för app/Dockerfile
    # mer info https://docs.docker.com/compose/compose-file/compose-file-v3/#short-syntax-3
    # denna version kör även nodemon så koden hot-reloadas vid save
        container_name: "stugmaklare-api-dev"
        image: node:latest
        restart: always
        ports:
            - 8080:8080
        networks:
            stugmaklare-public:
            stugmaklare-private:
                ipv4_address: 10.0.0.2
        volumes:
            - "./app:/home/node/app"
        profiles:
            - dev
        working_dir: "/home/node/app"
        command: "npm run dev"

    stugmaklare-db-dev:
        # Lånat lite därifrån
        # https://hub.docker.com/_/mongo
        container_name: "stugmaklare-db-dev"
        image: mongo:latest
        restart: unless-stopped
        profiles:
            - dev
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: toor
        ports:
            - 27017:27017
        networks:
            stugmaklare-private:
                ipv4_address: 10.0.0.3

# Services i stugmaklare har statiska ip addresser:
#   api -> 10.0.0.2
#   db  -> 10.0.0.3
networks:
    stugmaklare-public:
        name: stugmaklare-public
        external: true
    stugmaklare-private:
        name: stugmaklare-private
        external: false
        ipam:
            driver: default
            config:
                - subnet: 10.0.0.0/24