version: "3.9"

services:
    stugservice-api:
        container_name: "stugservice-api"
        # Lånat lite härifrån
        # https://github.com/nodejs/docker-node/blob/main/README.md#how-to-use-this-image
        build:
            context: .
            dockerfile: app/Dockerfile
        user: node
        environment:
            NODE_ENV: production
        restart: unless-stopped
        ports:
            - 8083:8083
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.wom2.rule=Host(`wom2.spionsatellit.com`)"
            - "traefik.http.routers.wom2.tls.domains[0].main=wom2.spionsatellit.com"
            - "traefik.http.routers.wom2.entrypoints=websecure"
            - "traefik.http.routers.wom2.tls=true"
            - "traefik.http.routers.wom2.tls.certresolver=myresolver"
            - "traefik.http.routers.wom2.tls.options=raitiovaunu-api@file"
            - "traefik.http.middlewares.wom1-compression.compress=true"
            - "traefik.http.routers.wom2.middlewares=wom1-compression"
        networks:
            - traefik-public
        command: "npm start"
        profiles:
          - prod

    stugservice-db:
        # Lånat lite därifrån
        # https://hub.docker.com/_/mongo
        container_name: "stugservice-db"
        image: mongo:latest
        restart: unless-stopped
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: toortoortoortoor11
        ports:
            - 27017:27017
        profiles:
            - prod
        networks:
            - traefik-public

    stugservice-api-dev:
    # !! OBS !! INSTALLERA PAKETEN LOKALT !! OBS !! NPM INSTALL KÖRS INTE I DENNA SERVICE !! OBS !!
    # samma som api bara att koden+node_modules mountas som volym istället, byggs även direkt från
    # node:latest istället för app/Dockerfile
    # mer info https://docs.docker.com/compose/compose-file/compose-file-v3/#short-syntax-3
    # denna version kör även nodemon så koden hot-reloadas vid save
        container_name: "stugservice-api-dev"
        image: node:latest
        user: node
        environment:
            NODE_ENV: development
        restart: always
        ports:
            - 8083:8083
        networks:
            - traefik-public
        volumes:
            - "./app:/home/node/app"
            - "./app/.npm:/home/node/app/.npm"
        profiles:
            - dev
        working_dir: "/home/node/app"
        command: "npm run dev-notest"

    stugservice-db-dev:
        # Lånat lite därifrån
        # https://hub.docker.com/_/mongo
        container_name: "stugservice-db-dev"
        image: mongo:latest
        restart: unless-stopped
        profiles:
            - dev
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: toor
        ports:
            - 27017:27017
        networks:
            - traefik-public

networks:
    traefik-public:
        external: true